# Generated by Django 5.1 on 2024-09-11 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_market', models.CharField(max_length=250)),
                ('account_number', models.CharField(max_length=16, unique=True)),
                ('amount', models.DecimalField(decimal_places=1, max_digits=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('reference_id', models.DecimalField(decimal_places=0, max_digits=10, unique=True)),
                ('last_market_ok', models.BooleanField(blank=True, default=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psp_transaction_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
