# Generated by Django 5.1 on 2024-08-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='from_market',
            field=models.CharField(max_length=250),
        ),
    ]
