# Generated by Django 5.1 on 2024-09-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bank_message',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='last_market_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference_id',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('not-confirm', 'Not-confirm')], default='pending', max_length=100),
        ),
    ]
