# Generated by Django 5.1 on 2024-09-18 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=16, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('cvv2', models.CharField(max_length=4)),
                ('balance', models.DecimalField(decimal_places=1, max_digits=20)),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('deactivate', 'Deactivate')], default='active', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_market', models.CharField(blank=True, max_length=250, null=True)),
                ('account_number', models.CharField(max_length=16, unique=True)),
                ('amount', models.DecimalField(decimal_places=1, max_digits=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('not-confirmed', 'Not-confirmed')], default='pending', max_length=100)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('reference_id', models.DecimalField(decimal_places=0, max_digits=10, unique=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_market_ok', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
